apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: {{ .Values.metadata.helloworld_app_namespace }}
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: {{ .Values.helloworld_app.replicas }}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - containerPort: 80
          resources:
            limits:
              cpu: '{{.Values.helloworld_app.resources.limits.cpu}}'
              memory: '{{.Values.helloworld_app.resources.limits.memory}}'
            requests:
              cpu: '{{.Values.helloworld_app.resources.requests.cpu}}'
              memory: '{{.Values.helloworld_app.resources.requests.memory}}'
